package nl.metafactory.aicontrol.model;

public enum GitWorkspaceJobErrorCode {
    NO_SELECTED_PROJECT,
    PROJECT_INACTIVE,
    PROJECT_NOT_FOUND,
    GIT_URL_MISSING,
    GIT_AUTH_FAILED,
    GIT_REPOSITORY_NOT_FOUND,
    GIT_CLONE_FAILED,
    BRANCH_CREATE_FAILED,
    SPEC_FILE_INVALID,
    AGENT_EXECUTION_FAILED,
    NO_CHANGES,
    COMMIT_FAILED,
    PUSH_FAILED,
    CONTAINER_CREATE_FAILED,
    CONTAINER_START_FAILED,
    CONTAINER_EXECUTION_FAILED,
    CLEANUP_FAILED,
    TIMEOUT,
    DOCKER_UNAVAILABLE,
    GIT_REPOSITORY_UNAVAILABLE
}