package nl.metafactory.aicontrol.model;

public enum SpecQueueFailureReason {
    WORKFLOW_INVALID,
    PREFLIGHT_FAILED,
    START_REJECTED,
    START_OUTCOME_UNKNOWN,
    RUN_FAILED,
    RUN_CANCELLED,
    APPROVAL_DENIED,
    RUN_BLOCKED,
    RUN_TIMED_OUT,
    RUN_STATE_LOST,
    PR_NOT_CREATED,
    PUBLICATION_FAILED,
    PR_URL_INVALID,
    PR_HOST_UNSUPPORTED,
    PR_CLOSED_UNMERGED,
    MERGE_CONFLICT,
    MERGE_BLOCKED,
    MERGE_WAIT_TIMEOUT,
    MERGE_AUTH_FAILED,
    MERGE_OUTCOME_UNKNOWN
}
