ALTER TABLE projects ADD COLUMN new_project SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN git_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE projects ADD COLUMN git_status_checked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE projects ADD COLUMN git_status_message VARCHAR(500);