import { Workspace } from './types';

export const mockWorkspace: Workspace = {
  customer: {
    id: 'noordzee-logistics',
    name: 'Noordzee Logistics B.V.',
    sector: 'Logistics & Transport',
    environment: 'Production',
    lastActive: 'today 13:24',
    dataClassification: 'Internal',
    region: 'eu-west-1',
  },
  selectedSpecFile: 'pricing-rules.spec.md',
  specs: [
    {
      id: 'pricing-rules',
      fileName: 'pricing-rules.spec.md',
      owner: 'Jan de Vries',
      lastChanged: '13:03',
      status: 'Active',
      selected: true,
      content:
        '# pricing-rules.spec.md\n\n## Business intent\n\nFor Noordzee Logistics B.V., pricing rules must be validated automatically before quotes are released.\n\n## Acceptance criteria\n\n- Rules above the configured risk threshold require review.\n- Changes are logged in release evidence.\n- Unit tests cover at least 90% of the relevant business rule logic.',
    },
    {
      id: 'customer-profile-update',
      fileName: 'customer-profile-update.spec.md',
      owner: 'Maria Bakker',
      lastChanged: '11:42',
      status: 'Open',
    },
    {
      id: 'approval-flow',
      fileName: 'approval-flow.spec.md',
      owner: 'Tom Janssen',
      lastChanged: '10:18',
      status: 'Open',
    },
    {
      id: 'shipment-tracking',
      fileName: 'shipment-tracking.spec.md',
      owner: 'Lisa van Dijk',
      lastChanged: 'Yesterday',
      status: 'Open',
    },
    {
      id: 'document-generation',
      fileName: 'document-generation.spec.md',
      owner: 'Pieter Smit',
      lastChanged: '2 May 13:21',
      status: 'Open',
    },
    {
      id: 'integration-webhooks',
      fileName: 'integration-webhooks.spec.md',
      owner: 'Arjan de Groot',
      lastChanged: '1 May 16:07',
      status: 'Open',
    },
  ],
  agents: [
    {
      kind: 'agent',
      id: 'requirement',
      name: 'Requirement Agent',
      description: 'Retrieve and validate requirements',
      status: 'Active',
      statusKind: 'active',
    },
    {
      kind: 'agent',
      id: 'impact',
      name: 'Impact Analysis Agent',
      description: 'Perform impact analysis',
      status: 'Active',
      statusKind: 'active',
    },
    {
      kind: 'agent',
      id: 'test-design',
      name: 'Test Design Agent',
      description: 'Design test scenarios',
      status: 'Active',
      statusKind: 'active',
    },
    {
      kind: 'agent',
      id: 'implementation',
      name: 'Implementation Agent',
      description: 'Generate & modify code',
      status: 'Active',
      statusKind: 'active',
    },
    {
      kind: 'agent',
      id: 'review',
      name: 'Review Agent',
      description: 'Code review & quality check',
      status: 'Done',
      statusKind: 'done',
    },
    {
      kind: 'agent',
      id: 'evidence',
      name: 'Evidence Agent',
      description: 'Collect & log evidence',
      status: 'Awaiting approval',
      statusKind: 'waiting',
    },
  ],
  pullRequests: [
    {
      id: '482',
      title: 'pricing-rules update',
      branch: 'feature/pricing-rules-update',
      createdAt: '13:02 today',
      ownerLabel: 'Author',
      ownerName: 'Jan de Vries',
      status: 'Open',
      statusKind: 'open',
    },
    {
      id: '487',
      title: 'add approval validation',
      branch: 'feature/approval-validation',
      createdAt: '11:47 today',
      ownerLabel: 'Reviewer',
      ownerName: 'Maria Bakker',
      status: 'In review',
      statusKind: 'review',
    },
    {
      id: '491',
      title: 'refine customer profile mapping',
      branch: 'feature/customer-profile-mapping',
      createdAt: '10:35 today',
      ownerLabel: 'Reviewer',
      ownerName: 'Tom Janssen',
      status: 'Changes requested',
      statusKind: 'changes',
    },
    {
      id: '476',
      title: 'update pricing engine',
      branch: 'feature/pricing-engine',
      createdAt: 'Yesterday 16:22',
      ownerLabel: 'Reviewer',
      ownerName: 'Lisa van Dijk',
      status: 'In review',
      statusKind: 'review',
    },
    {
      id: '468',
      title: 'add audit logging',
      branch: 'feature/audit-logging',
      createdAt: '2 May 14:08',
      ownerLabel: 'Author',
      ownerName: 'Pieter Smit',
      status: 'Open',
      statusKind: 'open',
    },
  ],
  evidenceEvents: [
    { time: '13:04', title: 'Spec loaded', actor: 'Requirement Agent', status: 'ok' },
    {
      time: '13:07',
      title: 'Impact analysis recorded',
      actor: 'Impact Analysis Agent',
      status: 'ok',
    },
    { time: '13:12', title: 'Test set generated', actor: 'Test Design Agent', status: 'ok' },
    {
      time: '13:16',
      title: 'Implementation proposal saved',
      actor: 'Implementation Agent',
      status: 'ok',
    },
    { time: '13:22', title: 'Human approval logged', actor: 'Review Agent', status: 'ok' },
    { time: '13:24', title: 'Evidence data recorded', actor: 'Evidence Agent', status: 'ok' },
  ],
  evidenceDetails: {
    specVersion: 'v1.3.2',
    runId: 'run_2025-05-06_1303',
    agentFlow: 'RQ → IA → TD → IMP → RV → EV',
    lastUpdate: '13:24 today',
  },
  qualityControls: [
    { name: 'Unit test coverage', status: 'Compliant', statusText: '92%' },
    { name: 'NIST 2', status: 'Compliant', statusText: '' },
    { name: 'OWASP ZAP', status: 'Compliant', statusText: 'No critical issues' },
    { name: 'ISO 25010', status: 'Compliant', statusText: '8/8 attributes' },
    { name: 'SAST', status: 'Compliant', statusText: 'No high issues' },
    { name: 'Dependency scan', status: 'Compliant', statusText: 'No known vulnerabilities' },
    { name: 'Architecture rules', status: 'Compliant', statusText: '0 deviations' },
  ],
  stack: [
    { name: 'Embabel Orchestrator', description: 'Orchestration of AI agents', status: 'live' },
    {
      name: 'Spring AI Control Service',
      description: 'Observability & Governance',
      status: 'live',
    },
  ],
  footer: {
    environment: 'Production',
    region: 'eu-west-1',
    dataClassification: 'Internal',
    embabelVersion: '2.4.1',
    springAiControlVersion: '1.8.3',
  },
};
