package nl.metafactory.agents.domain;

import java.util.List;

/** The code changes generated by the realisation agent for an implementation plan. */
public record CodeChangeSet(String summary, List<FileChange> changes) {}
